server:
  port: 8081
spring:
  profiles: dev
  application:
    name: eureka-server
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: dbc:mysql://localhost:3306/hyly?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Hongkong

eureka:
  instance:
    hostname: eureka-8081.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

---

server:
  port: 8081
spring:
  profiles: test
  application:
    name: eureka-server
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: dbc:mysql://localhost:3306/hyly?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Hongkong

eureka:
  instance:
    hostname: eureka-8081.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
