spring:
  profiles: dev  #开发环境
  application:
    name: bbs-dev
server:
  port: 8081
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ztkj?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

# logging:
#   config: classpath:log4j.properties

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      #配置主键生成策略
      id-type: uuid


---
spring:
  profiles: test  #测试环境
  application:
    name: com-syzw-test

#该文件必须另存为utf-8否则会出问题

---
spring:
  profiles: aa
  application:
    name: java
